/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ou1box.metrojourney;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        DoubleLinkedList SixTrain = new DoubleLinkedList();
        ArrayList<String> information = new ArrayList<String>();

        information.add("Brooklyn Bridge - City Hall");
        information.add("J");
        information.add("Z");
        information.add("4");
        information.add("5");
        SixTrain.append(information);

        ArrayList<String> informationn = new ArrayList<String>();
        informationn.add("Canal St");
        informationn.add("J");
        informationn.add("N");
        informationn.add("Q");
        informationn.add("R");
        informationn.add("W");
        SixTrain.append(informationn);

        SixTrain.announceUptown();
    }
}
